
version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydatabase
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
